import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing use of RecoScope and its benchmark data.",
};

export default function TermsPage() {
  return (
    <div className="bg-dot-grid">
      <article className="mx-auto max-w-3xl px-6 py-24">
        <p className="font-mono text-[11px] font-medium uppercase tracking-[0.2em] text-cyan/60">
          Legal
        </p>
        <h1 className="mt-4 text-4xl font-bold tracking-tight text-white">
          Terms of Service
        </h1>
        <p className="mt-4 text-[13px] text-white/30">Last updated: April 11, 2026</p>

        <div className="mt-12 space-y-10 text-[15px] leading-[1.8] text-[#c8ccd0]">
          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">What RecoScope does</h2>
            <p>
              RecoScope provides AI recommendation benchmark data for informational purposes only. We collect
              and analyze publicly available outputs from AI models (ChatGPT, Claude, Gemini, Perplexity, and
              others) to show which brands these models recommend across product categories.
            </p>
            <p className="mt-3">
              Our reports, rankings, and analysis do not constitute endorsements of any brand, product, or service.
              Brand rankings reflect AI model outputs at the time of testing and may change between reporting periods.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Data accuracy</h2>
            <p>
              AI model outputs are non-deterministic. The same prompt can produce different results on different
              days. Our benchmarks capture a snapshot, not a guaranteed prediction. We make reasonable efforts to
              ensure accuracy but do not guarantee that our data is complete, error-free, or representative of all
              possible AI responses.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Acceptable use</h2>
            <p>By using RecoScope, you agree not to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Scrape, crawl, or systematically download benchmark data</li>
              <li>Redistribute, republish, or commercially resell RecoScope reports without written permission</li>
              <li>Use the data to mislead consumers or make false advertising claims</li>
              <li>Attempt to reverse-engineer our prompts, methodology, or scoring algorithms</li>
              <li>Submit false information through any form on the site</li>
            </ul>
            <p className="mt-3">
              You may reference or cite RecoScope data in articles, presentations, and internal reports with
              appropriate attribution.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Free and paid access</h2>
            <p>
              RecoScope currently offers free access to published benchmark reports, newsletter subscriptions,
              and AI visibility audits. We may modify, limit, or discontinue free features at any time.
            </p>
            <p className="mt-3">
              Paid features (custom tracking, weekly reports, API access) are planned but not yet active.
              When launched, paid plans will have separate billing terms and pricing.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Intellectual property</h2>
            <p>
              The RecoScope name, logo, site design, original analysis, and editorial content are the property
              of RecoScope. The underlying AI model outputs we collect are generated by third-party systems
              (OpenAI, Anthropic, Google, Perplexity) and are subject to their respective terms.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Limitation of liability</h2>
            <p>
              RecoScope is provided &ldquo;as is&rdquo; without warranties of any kind, express or implied. To the
              maximum extent permitted by law, RecoScope and its operators shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages arising from your use of the site or
              reliance on our data.
            </p>
            <p className="mt-3">
              Our total liability for any claim related to the service shall not exceed the amount you paid
              us in the twelve months preceding the claim, or $100, whichever is greater.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Changes to these terms</h2>
            <p>
              We may update these terms from time to time. Material changes will be communicated via the site
              or email. Continued use of RecoScope after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-lg font-semibold text-white">Contact</h2>
            <p>
              Questions about these terms? Email{" "}
              <a href="mailto:contact@getrecoscope.com" className="text-cyan/60 underline underline-offset-2 hover:text-cyan">
                contact@getrecoscope.com
              </a>.
            </p>
          </section>
        </div>
      </article>
    </div>
  );
}
